AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 42

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Gemfile'

Style/Documentation:
  Enabled: false
