# frozen_string_literal: true

require_relative 'lib/legion/gaia/version'

Gem::Specification.new do |spec|
  spec.name = 'legion-gaia'
  spec.version       = Legion::Gaia::VERSION
  spec.authors       = ['Esity']
  spec.email         = ['matthewdiverson@gmail.com']
  spec.summary       = 'Cognitive coordination layer for the LegionIO framework'
  spec.description   = 'GAIA is the mind that inhabits the Legion body. Coordinates agentic subordinate functions, ' \
                       'drives the tick cycle, and provides channel abstraction for multi-interface communication.'
  spec.homepage      = 'https://github.com/LegionIO/legion-gaia'
  spec.license       = 'Apache-2.0'
  spec.require_paths = ['lib']
  spec.required_ruby_version = '>= 3.4'
  spec.files = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.extra_rdoc_files = %w[README.md LICENSE CHANGELOG.md]
  spec.metadata = {
    'bug_tracker_uri' => 'https://github.com/LegionIO/legion-gaia/issues',
    'changelog_uri' => 'https://github.com/LegionIO/legion-gaia/blob/main/CHANGELOG.md',
    'documentation_uri' => 'https://github.com/LegionIO/legion-gaia',
    'homepage_uri' => 'https://github.com/LegionIO/LegionIO',
    'source_code_uri' => 'https://github.com/LegionIO/legion-gaia',
    'wiki_uri' => 'https://github.com/LegionIO/legion-gaia/wiki',
    'rubygems_mfa_required' => 'true'
  }

  spec.add_dependency 'base64'
  spec.add_dependency 'legion-json'
  spec.add_dependency 'legion-logging'

  # Agentic cognitive extensions (full cognitive stack)
  spec.add_dependency 'lex-abductive-reasoning'
  spec.add_dependency 'lex-affordance'
  spec.add_dependency 'lex-agency'
  spec.add_dependency 'lex-analogical-reasoning'
  spec.add_dependency 'lex-anchoring'
  spec.add_dependency 'lex-anosognosia'
  spec.add_dependency 'lex-appraisal'
  spec.add_dependency 'lex-argument-mapping'
  spec.add_dependency 'lex-arousal'
  spec.add_dependency 'lex-attention'
  spec.add_dependency 'lex-attentional-blink'
  spec.add_dependency 'lex-attention-economy'
  spec.add_dependency 'lex-attention-regulation'
  spec.add_dependency 'lex-attention-schema'
  spec.add_dependency 'lex-attention-spotlight'
  spec.add_dependency 'lex-attention-switching'
  spec.add_dependency 'lex-bayesian-belief'
  spec.add_dependency 'lex-belief-revision'
  spec.add_dependency 'lex-bias'
  spec.add_dependency 'lex-causal-attribution'
  spec.add_dependency 'lex-causal-reasoning'
  spec.add_dependency 'lex-cognitive-alchemy'
  spec.add_dependency 'lex-cognitive-anchor'
  spec.add_dependency 'lex-cognitive-apprenticeship'
  spec.add_dependency 'lex-cognitive-archaeology'
  spec.add_dependency 'lex-cognitive-architecture'
  spec.add_dependency 'lex-cognitive-aurora'
  spec.add_dependency 'lex-cognitive-autopilot'
  spec.add_dependency 'lex-cognitive-avalanche'
  spec.add_dependency 'lex-cognitive-blindspot'
  spec.add_dependency 'lex-cognitive-boundary'
  spec.add_dependency 'lex-cognitive-catalyst'
  spec.add_dependency 'lex-cognitive-chrysalis'
  spec.add_dependency 'lex-cognitive-chunking'
  spec.add_dependency 'lex-cognitive-cocoon'
  spec.add_dependency 'lex-cognitive-coherence'
  spec.add_dependency 'lex-cognitive-compass'
  spec.add_dependency 'lex-cognitive-compression'
  spec.add_dependency 'lex-cognitive-constellation'
  spec.add_dependency 'lex-cognitive-contagion'
  spec.add_dependency 'lex-cognitive-control'
  spec.add_dependency 'lex-cognitive-debt'
  spec.add_dependency 'lex-cognitive-debugging'
  spec.add_dependency 'lex-cognitive-defusion'
  spec.add_dependency 'lex-cognitive-disengagement'
  spec.add_dependency 'lex-cognitive-dissonance-resolution'
  spec.add_dependency 'lex-cognitive-dwell'
  spec.add_dependency 'lex-cognitive-echo'
  spec.add_dependency 'lex-cognitive-echo-chamber'
  spec.add_dependency 'lex-cognitive-empathy'
  spec.add_dependency 'lex-cognitive-entrainment'
  spec.add_dependency 'lex-cognitive-erosion'
  spec.add_dependency 'lex-cognitive-fatigue-model'
  spec.add_dependency 'lex-cognitive-fermentation'
  spec.add_dependency 'lex-cognitive-fingerprint'
  spec.add_dependency 'lex-cognitive-flexibility'
  spec.add_dependency 'lex-cognitive-flexibility-training'
  spec.add_dependency 'lex-cognitive-fossil-fuel'
  spec.add_dependency 'lex-cognitive-friction'
  spec.add_dependency 'lex-cognitive-furnace'
  spec.add_dependency 'lex-cognitive-garden'
  spec.add_dependency 'lex-cognitive-genesis'
  spec.add_dependency 'lex-cognitive-grammar'
  spec.add_dependency 'lex-cognitive-gravity'
  spec.add_dependency 'lex-cognitive-greenhouse'
  spec.add_dependency 'lex-cognitive-hologram'
  spec.add_dependency 'lex-cognitive-homeostasis'
  spec.add_dependency 'lex-cognitive-horizon'
  spec.add_dependency 'lex-cognitive-hourglass'
  spec.add_dependency 'lex-cognitive-immune-memory'
  spec.add_dependency 'lex-cognitive-immune-response'
  spec.add_dependency 'lex-cognitive-immunology'
  spec.add_dependency 'lex-cognitive-inertia'
  spec.add_dependency 'lex-cognitive-integration'
  spec.add_dependency 'lex-cognitive-kaleidoscope'
  spec.add_dependency 'lex-cognitive-labyrinth'
  spec.add_dependency 'lex-cognitive-lens'
  spec.add_dependency 'lex-cognitive-lighthouse'
  spec.add_dependency 'lex-cognitive-liminal'
  spec.add_dependency 'lex-cognitive-load'
  spec.add_dependency 'lex-cognitive-load-balancing'
  spec.add_dependency 'lex-cognitive-lucidity'
  spec.add_dependency 'lex-cognitive-magnet'
  spec.add_dependency 'lex-cognitive-map'
  spec.add_dependency 'lex-cognitive-metabolism'
  spec.add_dependency 'lex-cognitive-mirror'
  spec.add_dependency 'lex-cognitive-momentum'
  spec.add_dependency 'lex-cognitive-mosaic'
  spec.add_dependency 'lex-cognitive-mycelium'
  spec.add_dependency 'lex-cognitive-narrative-arc'
  spec.add_dependency 'lex-cognitive-nostalgia'
  spec.add_dependency 'lex-cognitive-offloading'
  spec.add_dependency 'lex-cognitive-origami'
  spec.add_dependency 'lex-cognitive-paleontology'
  spec.add_dependency 'lex-cognitive-palimpsest'
  spec.add_dependency 'lex-cognitive-pendulum'
  spec.add_dependency 'lex-cognitive-phantom'
  spec.add_dependency 'lex-cognitive-plasticity'
  spec.add_dependency 'lex-cognitive-prism'
  spec.add_dependency 'lex-cognitive-quicksand'
  spec.add_dependency 'lex-cognitive-quicksilver'
  spec.add_dependency 'lex-cognitive-reappraisal'
  spec.add_dependency 'lex-cognitive-reserve'
  spec.add_dependency 'lex-cognitive-resonance'
  spec.add_dependency 'lex-cognitive-rhythm'
  spec.add_dependency 'lex-cognitive-scaffolding'
  spec.add_dependency 'lex-cognitive-surplus'
  spec.add_dependency 'lex-cognitive-symbiosis'
  spec.add_dependency 'lex-cognitive-synesthesia'
  spec.add_dependency 'lex-cognitive-synthesis'
  spec.add_dependency 'lex-cognitive-tapestry'
  spec.add_dependency 'lex-cognitive-tectonics'
  spec.add_dependency 'lex-cognitive-telescope'
  spec.add_dependency 'lex-cognitive-tempo'
  spec.add_dependency 'lex-cognitive-tessellation'
  spec.add_dependency 'lex-cognitive-tide'
  spec.add_dependency 'lex-cognitive-triage'
  spec.add_dependency 'lex-cognitive-volcano'
  spec.add_dependency 'lex-cognitive-weather'
  spec.add_dependency 'lex-cognitive-weathering'
  spec.add_dependency 'lex-cognitive-whirlpool'
  spec.add_dependency 'lex-cognitive-zeitgeist'
  spec.add_dependency 'lex-coldstart'
  spec.add_dependency 'lex-conceptual-blending'
  spec.add_dependency 'lex-conceptual-metaphor'
  spec.add_dependency 'lex-confabulation'
  spec.add_dependency 'lex-conflict'
  spec.add_dependency 'lex-conscience'
  spec.add_dependency 'lex-consent'
  spec.add_dependency 'lex-context'
  spec.add_dependency 'lex-cortex'
  spec.add_dependency 'lex-counterfactual'
  spec.add_dependency 'lex-creativity'
  spec.add_dependency 'lex-curiosity'
  spec.add_dependency 'lex-decision-fatigue'
  spec.add_dependency 'lex-default-mode-network'
  spec.add_dependency 'lex-dissonance'
  spec.add_dependency 'lex-distributed-cognition'
  spec.add_dependency 'lex-dream'
  spec.add_dependency 'lex-dual-process'
  spec.add_dependency 'lex-embodied-simulation'
  spec.add_dependency 'lex-emotion'
  spec.add_dependency 'lex-emotional-regulation'
  spec.add_dependency 'lex-empathy'
  spec.add_dependency 'lex-enactive-cognition'
  spec.add_dependency 'lex-episodic-buffer'
  spec.add_dependency 'lex-epistemic-curiosity'
  spec.add_dependency 'lex-epistemic-vigilance'
  spec.add_dependency 'lex-error-monitoring'
  spec.add_dependency 'lex-executive-function'
  spec.add_dependency 'lex-expectation-violation'
  spec.add_dependency 'lex-extinction'
  spec.add_dependency 'lex-fatigue'
  spec.add_dependency 'lex-feature-binding'
  spec.add_dependency 'lex-flow'
  spec.add_dependency 'lex-frame-semantics'
  spec.add_dependency 'lex-free-energy'
  spec.add_dependency 'lex-gestalt'
  spec.add_dependency 'lex-global-workspace'
  spec.add_dependency 'lex-goal-management'
  spec.add_dependency 'lex-governance'
  spec.add_dependency 'lex-habit'
  spec.add_dependency 'lex-hebbian-assembly'
  spec.add_dependency 'lex-homeostasis'
  spec.add_dependency 'lex-hypothesis-testing'
  spec.add_dependency 'lex-identity'
  spec.add_dependency 'lex-imagination'
  spec.add_dependency 'lex-inhibition'
  spec.add_dependency 'lex-inner-speech'
  spec.add_dependency 'lex-interoception'
  spec.add_dependency 'lex-intuition'
  spec.add_dependency 'lex-joint-attention'
  spec.add_dependency 'lex-language'
  spec.add_dependency 'lex-latent-inhibition'
  spec.add_dependency 'lex-learning-rate'
  spec.add_dependency 'lex-memory'
  spec.add_dependency 'lex-mentalizing'
  spec.add_dependency 'lex-mental-simulation'
  spec.add_dependency 'lex-mental-time-travel'
  spec.add_dependency 'lex-mesh'
  spec.add_dependency 'lex-metacognition'
  spec.add_dependency 'lex-metacognitive-monitoring'
  spec.add_dependency 'lex-meta-learning'
  spec.add_dependency 'lex-mind-growth'
  spec.add_dependency 'lex-mirror'
  spec.add_dependency 'lex-mood'
  spec.add_dependency 'lex-moral-reasoning'
  spec.add_dependency 'lex-motivation'
  spec.add_dependency 'lex-narrative-identity'
  spec.add_dependency 'lex-narrative-reasoning'
  spec.add_dependency 'lex-narrative-self'
  spec.add_dependency 'lex-narrator'
  spec.add_dependency 'lex-neural-oscillation'
  spec.add_dependency 'lex-neuromodulation'
  spec.add_dependency 'lex-perceptual-inference'
  spec.add_dependency 'lex-personality'
  spec.add_dependency 'lex-perspective-shifting'
  spec.add_dependency 'lex-phenomenal-binding'
  spec.add_dependency 'lex-planning'
  spec.add_dependency 'lex-pragmatic-inference'
  spec.add_dependency 'lex-prediction'
  spec.add_dependency 'lex-predictive-coding'
  spec.add_dependency 'lex-predictive-processing'
  spec.add_dependency 'lex-preference-learning'
  spec.add_dependency 'lex-priming'
  spec.add_dependency 'lex-privatecore'
  spec.add_dependency 'lex-procedural-learning'
  spec.add_dependency 'lex-prospection'
  spec.add_dependency 'lex-prospective-memory'
  spec.add_dependency 'lex-qualia'
  spec.add_dependency 'lex-reality-testing'
  spec.add_dependency 'lex-reflection'
  spec.add_dependency 'lex-relevance-theory'
  spec.add_dependency 'lex-resilience'
  spec.add_dependency 'lex-reward'
  spec.add_dependency 'lex-salience'
  spec.add_dependency 'lex-schema'
  spec.add_dependency 'lex-self-model'
  spec.add_dependency 'lex-self-talk'
  spec.add_dependency 'lex-semantic-memory'
  spec.add_dependency 'lex-semantic-priming'
  spec.add_dependency 'lex-semantic-satiation'
  spec.add_dependency 'lex-sensory-gating'
  spec.add_dependency 'lex-signal-detection'
  spec.add_dependency 'lex-situation-model'
  spec.add_dependency 'lex-social'
  spec.add_dependency 'lex-social-learning'
  spec.add_dependency 'lex-somatic-marker'
  spec.add_dependency 'lex-source-monitoring'
  spec.add_dependency 'lex-subliminal'
  spec.add_dependency 'lex-surprise'
  spec.add_dependency 'lex-swarm'
  spec.add_dependency 'lex-swarm-github'
  spec.add_dependency 'lex-temporal'
  spec.add_dependency 'lex-temporal-discounting'
  spec.add_dependency 'lex-theory-of-mind'
  spec.add_dependency 'lex-tick'
  spec.add_dependency 'lex-transfer-learning'
  spec.add_dependency 'lex-trust'
  spec.add_dependency 'lex-uncertainty-tolerance'
  spec.add_dependency 'lex-volition'
  spec.add_dependency 'lex-working-memory'
end
